Add a .clang-format file and a 'make clang-format' target (#2053)
* Add a .clang-format file and a 'make clang-format' target

clang-format is a part of the LLVM/Clang compiler suite that will
reformat your code -- but much better than most code reformatters,
because this one is based on a compiler toolkit and is working on the
fully understood AST, not just text.

The idea here is that we give up a little bit of individual creativity
in code formatting, in exchange for every pull request trivially being
able to conform to the house style and never having to go through
multiple rounds of PR edits for formatting issues, nor ever have any
squabbles about it. I know that nobody will be 100% happy with the
require formatting (even me), but I think if we can make everybody 80%
happy and avoid those other problems forever after, it's worth it.
People I respect running othe projects consistently swear that adopting
clang-format was one of the best decisions they made.

Basically, after the initial cmake configuration, you can reformat
files with

    make clang-format

Configuration variables CLANG_FORMAT_INCLUDES and CLANG_FORMAT_EXCLUDES
let you customize the lists of glob patterns that get included, or
excluded, from reformatting. For example, if you only want to reformat
one file (and you should try this to see how the whole thing works!):

    make nuke
    make CLANG_FORMAT_INCLUDES="exrinput.cpp" clang-format

Currently, I'm thinking that public header files will NOT be reformatted
(i.e. the exclude list will default to including src/include).  I just
can't seem to get fully satisfied with the transformations, and I think
that's because I think of public headers as documentation, so I'm
extremely picky about the formatting and think that readability is
paramount, so I make little one-off rule breaks all the time to improve
the flow, readability, and appearance. Of public headers. I think for
everything else, I'm willing to live with a set of rigid rules.

I'm still experimenting with getting the parameters right. I may keep
tinkering a bit before committing any actual reformatting. For that
reason, I'm merely proposing the build script and style configuration
portions now. Only after people have tried it out and we think we can
live with it, will I do the great reformatting checkin.

Also, eventually, we'll make one of the Travis-CI tests do a
clang-format and fail if anything needs to be changed (and print the
diffs), thus making the CI make it very clear when any PR fails to
conform, and we will expect the submitter to run clang-format (or change
the offending parts by hand) and resubmit.

Addenda:

Make one Travis test matrix entry that only configures cmake and then
does a 'make clang-format'. Rig it so that if there are diffs produced
(i.e., the PR was not 100% conformant), it prints the diffs for
inspection and fails the test. If running clang-format produced no
changes to the source, the diffs will be empty and the test passes.

Also discovered the `name:` way of labeling Travis tests! Makes the
dashboard more readable.

Currently, no files are in the CLANG_FORMAT_INCLUDES list, so everything
should pass.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -51,6 +51,7 @@ cache:
 before_install:
     - if [ "$WHICHGCC" == "" ]; then export WHICHGCC="4.8" ; fi
     - if [ "$PYTHON_VERSION" == "" ]; then export PYTHON_VERSION="2.7" ; fi
+    - if [ "$BUILD_MISSING_DEPS" == "" ] ; then export BUILD_MISSING_DEPS=1 ; fi
     - if [ $TRAVIS_OS_NAME == osx ] ; then
           uname -n ;
           export PLATFORM=macosx ;
@@ -87,18 +88,21 @@ install:
 
 script:
     - make VERBOSE=1 $BUILD_FLAGS BUILD_MISSING_DEPS=1 cmakesetup
-    - make -j2 $BUILD_FLAGS
+    - make -j2 $BUILD_FLAGS $OIIOTARGET
     - export OPENIMAGEIO_ROOT_DIR=$PWD/dist/$PLATFORM
-    - export DYLD_LIBRARY_PATH=$OPENIMAGEIO_ROOT_DIR/lib:$DYLD_LIBRARY_PATH 
+    - export DYLD_LIBRARY_PATH=$OPENIMAGEIO_ROOT_DIR/lib:$DYLD_LIBRARY_PATH
     - export LD_LIBRARY_PATH=$OPENIMAGEIO_ROOT_DIR/lib:$LD_LIBRARY_PATH
     - export OIIO_LIBRARY_PATH=$OPENIMAGEIO_ROOT_DIR/lib
-    - echo "OIIO_LIBRARY_PATH is ${OIIO_LIBRARY_PATH}"
-    # - echo "list of library path:"
-    # - ls -R $OIIO_LIBRARY_PATH
     - export PYTHONPATH=$OPENIMAGEIO_ROOT_DIR/python:$PYTHONPATH
     - export LSAN_OPTIONS=suppressions=$PWD/src/build-scripts/nosanitize.txt
     - if [ "$SKIP_TESTS" == "" ] ; then
           make $BUILD_FLAGS test ;
+      fi
+    - git diff --color ;
+      THEDIFF=`git diff` ;
+      if [ "$THEDIFF" != "" ] ; then
+          echo "git diff was not empty. Failing clang-format check." ;
+          exit 1 ;
       fi
 
 
@@ -124,30 +128,36 @@ matrix:
 
     include:
     # test default compile: C++11, optimized, default compilers, SSE2
-      - os: linux
+      - name: "Linux Standard (gcc48, py27)"
+        os: linux
         compiler: gcc
-      - os: osx
+      - name: "Mac (latest clang, py37)"
+        os: osx
         compiler: clang
         env: PYTHON_VERSION=3.7
     # Make sure Python 2.7 still works on OSX, but only for PRs, master/RB
     # pushes, or if the branch name includes "python".
-      - os: osx
+      - name: "Mac py27 (latest clang)"
+        os: osx
         compiler: clang
         env: PYTHON_VERSION=2.7
         if: branch =~ /(master|RB|travis|python)/ OR type = pull_request
     # test debug build with default compiler
-      - os: linux
+      - name: "Linux DEBUG Standard"
+        os: linux
         compiler: gcc
         env: DEBUG=1
       # - os: osx
       #   compiler: clang
       #   env: DEBUG=1
     # test with C++14, gcc 6, SSE 4.2
-      - os: linux
+      - name: "VFX Platform 2018 (gcc6, cpp14), sse4.2"
+        os: linux
         compiler: gcc
         env: WHICHGCC=6 USE_CPP=14 USE_SIMD=sse4.2
     # test with C++14, gcc 7, latest SIMD flags supported by TravisCI VMs
-      - os: linux
+      - name: "gcc7, cpp14, avx"
+        os: linux
         compiler: gcc
         env: WHICHGCC=7 USE_CPP=14 USE_SIMD=avx,f16c
     # Test LINKSTATIC on both platforms. This is incomplete and to make it
@@ -168,7 +178,8 @@ matrix:
     # pushes to master or RB branches, or if the branch name includes
     # "sanitize". Other ordinary work branch pushes don't need to run this
     # every time.
-      - os: linux
+      - name: "Sanitizers"
+        os: linux
         compiler: gcc
         env: WHICHGCC=6 SANITIZE=address USE_PYTHON=0
         if: branch =~ /(master|RB|travis|san)/ OR type = pull_request
@@ -180,7 +191,8 @@ matrix:
     # Only build this case for PRs, direct pushes to master or RB branches,
     # or if the branch name includes "simd". Other ordinary work branch
     # pushes don't need to run this.
-      - os: linux
+      - name: "Test no simd, no jpegturbo, dso plugins"
+        os: linux
         compiler: gcc
         env: USE_SIMD=0 USE_JPEGTURBO=0 EMBEDPLUGINS=0
         if: branch =~ /(master|RB|travis|simd)/ OR type = pull_request
@@ -189,7 +201,8 @@ matrix:
     # case for PRs, direct pushes to master or RB branches, or if the branch
     # name includes "gcc". Other ordinary work branch pushes don't
     # need to run this.
-      - os: linux
+      - name: "Linux gcc8 cpp14 avx"
+        os: linux
         compiler: gcc
         env: WHICHGCC=8 USE_CPP=14 USE_SIMD=avx,f16c
         if: branch =~ /(master|RB|travis|gcc)/ OR type = pull_request
@@ -198,7 +211,8 @@ matrix:
     # case for PRs, direct pushes to master or RB branches, or if the branch
     # name includes "17" or "gcc". Other ordinary work branch pushes don't
     # need to run this.
-      - os: linux
+      - name: "Linux most advanced (gcc8, cpp17, avx/f16c)"
+        os: linux
         compiler: gcc
         env: WHICHGCC=8 USE_CPP=17 USE_SIMD=avx,f16c
         if: branch =~ /(master|RB|travis|gcc|17)/ OR type = pull_request
@@ -206,7 +220,8 @@ matrix:
     # Only build this case for PRs, direct pushes to master or RB branches,
     # or if the branch name includes "simd". Other ordinary work branch
     # pushes don't need to run this.
-      - os: linux
+      - name: "Build clean AVX2"
+        os: linux
         compiler: gcc
         env: WHICHGCC=6 USE_SIMD=avx2 SKIP_TESTS=1
         if: branch =~ /(master|RB|travis|simd)/ OR type = pull_request
@@ -214,10 +229,17 @@ matrix:
     # Only build this case for PRs, direct pushes to master or RB branches,
     # or if the branch name includes "simd". Other ordinary work branch
     # pushes don't need to run this.
-      - os: linux
+      - name: "Build clean vs AVX512"
+        os: linux
         compiler: gcc
         env: WHICHGCC=7 USE_SIMD=avx2,avx512f,f16c SKIP_TESTS=1
         if: branch =~ /(master|RB|travis|simd)/ OR type = pull_request
+    # Just run clang-format, this test only checks formatting rule conformance
+      - name: "clang-format format verification"
+        os: osx
+        compiler: clang
+        env: OIIOTARGET=clang-format SKIP_TESTS=1 BUILD_MISSING_DEPS=0
+        #if: branch =~ /(master|RB|travis|simd)/ OR type = pull_request
     # Build with EMBEDPLUGINS=0, both platforms.
       # FIXME: doesn't work yet on Travis
       # - os: linux
