ci: For python wheel generation, use ccache
Building the python wheels takes a long time! I really hate waiting
for that to get added to the CI, there must be a way to speed it up.

* To wheel workflow, add cache actions to save and restore the
  CCACHE_DIR. Hey, it's no easy feat to figure out what the path
  should be to that directory, especially on Linux where the wheels
  are build in a container, so the paths in the container (where the
  wheel is built and the C++ compilation happens) don't match the
  paths outside the container (where the cache restore and save
  actions execute).

* I had a heck of a time on Linux trying to get a pre-built ccache
  installed and had to resort to writing a bash script to build ccache
  itself from scratch.

* Changed our "auto-build" utility build_dependency_with_cmake to
  print the amount of time it takes to build each dependency.

* When auto-building, pass along CMAKE_CXX_COMPILER_LAUNCHER so that
  the dependenencies also for sure use ccache.

* Use CMAKE_BUILD_PARALLEL_LEVEL on the wheel run to use all the cores
  and compile in parallel. (We did that on the regular CI but I think
  not for the wheel building.)

* Fixes to the logic in our compiler.cmake where it tries to use
  ccache even if the magic CMAKE_CXX_COMPILER_LAUNCHER isn't set -- I
  now believe we were doing it wrong, it was having no effect, and all
  along we only got ccache working on CI because we *also* set the env
  variable.

* For CI, set CCACHE_COMPRESSION=1 to make the caches take less space
  against the precious limit of how much cache we can use total on
  GHA.

So, the result of all this:

**Previous times (typical)**

| platform    | total | compile OIIO + deps |
| ----------- | ----- | ------------------- |
| Linux Intel | 10:35 |  500s               |
| Linux ARM   |  7:20 |  294s               |
| Mac Intel   | 20:18 | 1146s               |
| Mac ARM     |  7:19 |  388s               |
| Windows     | 14:00 |  759s               |

**With ccache active**

| platform    | total | compile OIIO + deps |
| ----------- | ----- | ------------------- |
| Linux Intel |  3:33 |  98s                |
| Linux ARM   |  3:34 |  83s                |
| Mac Intel   |  5:01 | 212s                |
| Mac ARM     |  2:30 |  95s                |
| Windows     |   N/A | not using ccache    |

The "compile OIIO + deps" column is the isolated time to build OIIO
and also any auto-building of dependencies from source that we do. But
it does not include any other setup, such as 40-60s of container setup
on Linux, 20-40s setting up Python on Mac, or -- ick! -- 45-60 seconds
to build cmake itself from scratch.

So this is considerably better, speeding up the full wheel workflow by
2-4x on all platforms but Windows. Remaining room for improvement:

* Is there a way to use ccache on Windows? I'm not sure if there is,
  when using MSVS.
* Find a way to install pre-built binaries on Linux rather than building
  ccache from scratch, which would save almost a whole minute per job.
* Organize each platform to build all of its wheels (i.e. all of the
  python versions we are building for on that platform) in a single
  job rather than as completely independent jobs, allowing (a) the
  fixed per-job overhead such as container initialization, and
  installing python, and building of certain dependencies to happen
  ONCE per platform instead of separately for each wheel, and (b) the
  magic of ccache to speed up the builds *across* those wheels, since
  only a tiny amount of OIIO source codes depend on python at all.

Signed-off-by: Larry Gritz <lg@larrygritz.com>

diff --git a/.github/workflows/wheel.yml b/.github/workflows/wheel.yml
--- a/.github/workflows/wheel.yml
+++ b/.github/workflows/wheel.yml
@@ -39,6 +39,12 @@ on:
   workflow_dispatch:
     # This allows manual triggering of the workflow from the web
 
+# Allow subsequent pushes to the same PR or REF to cancel any previous jobs.
+concurrency:
+  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
+  cancel-in-progress: true
+
+
 jobs:
   # Linux jobs run in Docker containers (manylinux), so the latest OS version
   # is OK. macOS and Windows jobs need to be locked to specific virtual
@@ -141,6 +147,14 @@ jobs:
         with:
           python-version: '3.9'
 
+      - name: ccache-restore
+        id: ccache-restore
+        uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
+        with:
+          path: ~/.ccache
+          key: wheel-${{runner.os}}-${{matrix.manylinux}}-${{matrix.python}}
+          restore-keys: wheel-${{runner.os}}-${{matrix.manylinux}}-${{matrix.python}}
+
       - name: Build wheels
         # Note: the version of cibuildwheel should be kept in sync with src/python/stubs/CMakeLists.txt
         uses: pypa/cibuildwheel@d4a2945fcc8d13f20a1b99d461b8e844d5fc6e23 # v2.21.1
@@ -148,13 +162,35 @@ jobs:
           # pass GITHUB_ACTIONS through to the build container so that custom
           # processes can tell they are running in CI.
           CIBW_ENVIRONMENT_PASS_LINUX: GITHUB_ACTIONS
+          CIBW_BEFORE_ALL: "source src/build-scripts/build_ccache.bash && pwd && ext/dist/bin/ccache --max-size=200M && ext/dist/bin/ccache -sv && export CMAKE_C_COMPILER_LAUNCHER=/project/ext/dist/bin/ccache CMAKE_CXX_COMPILER_LAUNCHER=/project/ext/dist/bin/ccache"
+          CIBW_BEFORE_TEST: "ext/dist/bin/ccache -s"
           CIBW_BUILD: ${{ matrix.python }}
           CIBW_ARCHS: ${{ matrix.arch }}
           CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.manylinux }}
+          CIBW_ENVIRONMENT: >
+              CCACHE_DIR=/host//home/runner/.ccache
+              CCACHE_COMPRESSION=yes
+              CCACHE_PREBUILT=0
+              CMAKE_BUILD_PARALLEL_LEVEL=4
+              CTEST_PARALLEL_LEVEL=4
+              SKBUILD_CMAKE_ARGS="-DLINKSTATIC=1"
+              SKBUILD_CMAKE_BUILD_TYPE="MinSizeRel"
+              SKBUILD_BUILD_DIR=/project/build
+              CXXFLAGS="-Wno-error=stringop-overflow -Wno-pragmas"
+              WebP_BUILD_VERSION="1.5.0"
+          # FIXME: Getting build problems when using WebP 1.6.0, so hold it back
+          # CMAKE_GENERATOR = "Ninja"
+
+      - name: ccache-save
+        id: ccache-save
+        uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
+        with:
+          path: ~/.ccache
+          key: wheel-${{runner.os}}-${{matrix.manylinux}}-${{matrix.python}}
 
       - uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
         with:
-          name: cibw-wheels-${{ matrix.python }}-${{ matrix.manylinux }}
+          name: cibw-wheels-${{matrix.manylinux}}-${{ matrix.python }}-${{ matrix.manylinux }}
           path: |
             ./wheelhouse/*.whl
 
@@ -173,12 +209,12 @@ jobs:
   # ---------------------------------------------------------------------------
 
   linux-arm:
-      name: Build wheels on Linux ARM
-      runs-on: ubuntu-24.04-arm
-      if: |
-        github.event_name != 'schedule' ||
-        github.repository == 'AcademySoftwareFoundation/OpenImageIO'
-      strategy:
+    name: Build wheels on Linux ARM
+    runs-on: ubuntu-24.04-arm
+    if: |
+      github.event_name != 'schedule' ||
+      github.repository == 'AcademySoftwareFoundation/OpenImageIO'
+    strategy:
         matrix:
           include:
             # -------------------------------------------------------------------
@@ -205,37 +241,66 @@ jobs:
               python: cp313-manylinux_aarch64
               arch: aarch64
 
-      steps:
-        - name: Checkout repo
-          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+    steps:
+      - name: Checkout repo
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
 
-        - name: Install Python
-          uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
-          with:
-            python-version: '3.9'
+      - name: Install Python
+        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
+        with:
+          python-version: '3.9'
         
-        - name: Build wheels
-          uses: pypa/cibuildwheel@d4a2945fcc8d13f20a1b99d461b8e844d5fc6e23 # v2.21.1
-          env:
-            CIBW_BUILD: ${{ matrix.python }}
-            CIBW_ARCHS: ${{ matrix.arch }}
-            CIBW_MANYLINUX_AARCH64_IMAGE: ${{ matrix.manylinux }}
+      - name: ccache-restore
+        id: ccache-restore
+        uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
+        with:
+          path: ~/.ccache
+          key: wheel-${{runner.os}}-${{matrix.python}}
+          restore-keys: wheel-${{runner.os}}-${{matrix.python}}
 
-        - uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
-          with:
-            name: cibw-wheels-${{ matrix.python }}-${{ matrix.manylinux }}
-            path: |
-              ./wheelhouse/*.whl
-        
-        - uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
-          with:
-            name: stubs-${{ matrix.python }}-${{ matrix.manylinux }}
-            path: |
-              ./wheelhouse/OpenImageIO/__init__.pyi
-          # if stub validation fails we want to upload the stubs for users to review.
-          # keep the python build in sync with the version specified in tool.cibuildwheel.overrides 
-          # section of pyproject.toml
-          if: always() && contains(matrix.python, 'cp311-manylinux')
+      - name: Build wheels
+        uses: pypa/cibuildwheel@d4a2945fcc8d13f20a1b99d461b8e844d5fc6e23 # v2.21.1
+        env:
+          CIBW_ENVIRONMENT_PASS_LINUX: GITHUB_ACTIONS
+          CIBW_BEFORE_ALL: "source src/build-scripts/build_ccache.bash && pwd && /project/ext/dist/bin/ccache --max-size=200M && /project/ext/dist/bin/ccache -sv && export CMAKE_C_COMPILER_LAUNCHER=/project/ext/dist/bin/ccache CMAKE_CXX_COMPILER_LAUNCHER=/project/ext/dist/bin/ccache"
+          CIBW_BEFORE_TEST: "ext/dist/bin/ccache -s"
+          CIBW_BUILD: ${{ matrix.python }}
+          CIBW_ARCHS: ${{ matrix.arch }}
+          CIBW_MANYLINUX_AARCH64_IMAGE: ${{ matrix.manylinux }}
+          CIBW_ENVIRONMENT: >
+              CCACHE_DIR=/host//home/runner/.ccache
+              CCACHE_COMPRESSION=yes
+              CCACHE_PREBUILT=0
+              CMAKE_BUILD_PARALLEL_LEVEL=6
+              CTEST_PARALLEL_LEVEL=6
+              SKBUILD_CMAKE_ARGS="-DLINKSTATIC=1"
+              SKBUILD_CMAKE_BUILD_TYPE="MinSizeRel"
+              SKBUILD_BUILD_DIR=/project/build
+              CXXFLAGS="-Wno-error=stringop-overflow -Wno-pragmas"
+              WebP_BUILD_VERSION="1.5.0"
+
+      - name: ccache-save
+        id: ccache-save
+        uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
+        with:
+          path: ~/.ccache
+          key: wheel-${{runner.os}}-${{matrix.python}}
+
+      - uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
+        with:
+          name: cibw-wheels-${{ matrix.python }}-${{ matrix.manylinux }}
+          path: |
+            ./wheelhouse/*.whl
+      
+      - uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
+        with:
+          name: stubs-${{ matrix.python }}-${{ matrix.manylinux }}
+          path: |
+            ./wheelhouse/OpenImageIO/__init__.pyi
+        # if stub validation fails we want to upload the stubs for users to review.
+        # keep the python build in sync with the version specified in tool.cibuildwheel.overrides 
+        # section of pyproject.toml
+        if: always() && contains(matrix.python, 'cp311-manylinux')
 
   # ---------------------------------------------------------------------------
   # macOS Wheels
@@ -278,6 +343,18 @@ jobs:
         with:
           python-version: '3.9'
 
+      - name: ccache-restore
+        id: ccache-restore
+        uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
+        with:
+          path: ~/.ccache
+          key: wheel-${{runner.os}}-${{matrix.python}}
+          restore-keys: wheel-${{runner.os}}-${{matrix.python}}
+
+      - name: Install build tools
+        run: |
+            brew install ninja ccache || true
+        
       - name: Remove brew OpenEXR/Imath
         run: |
             brew uninstall --ignore-dependencies openexr imath || true
@@ -292,6 +369,18 @@ jobs:
           # TODO: Re-enable HEIF when we provide a build recipe that does 
           # not include GPL-licensed dynamic libraries.
           USE_Libheif: 'OFF'
+          CMAKE_BUILD_PARALLEL_LEVEL: 6
+          CTEST_PARALLEL_LEVEL: 6
+          SKBUILD_BUILD_DIR: "/Users/runner/work/OpenImageIO/OpenImageIO/build"
+          CCACHE_DIR: /Users/runner/.ccache
+          CCACHE_COMPRESSION: yes
+
+      - name: ccache-save
+        id: ccache-save
+        uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
+        with:
+          path: ~/.ccache
+          key: wheel-${{runner.os}}-${{matrix.python}}
 
       - uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
         with:
@@ -340,13 +429,36 @@ jobs:
         with:
           python-version: '3.9'
         
+      - name: ccache-restore
+        id: ccache-restore
+        uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
+        with:
+          path: ~/.ccache
+          key: wheel-${{runner.os}}-${{matrix.python}}
+          restore-keys: wheel-${{runner.os}}-${{matrix.python}}
 
+      - name: Install build tools
+        run: |
+            brew install ninja ccache || true
+        
       - name: Build wheels
         uses: pypa/cibuildwheel@d4a2945fcc8d13f20a1b99d461b8e844d5fc6e23 # v2.21.1
         env:
           CIBW_BUILD: ${{ matrix.python }}
           CIBW_ARCHS: ${{ matrix.arch }}
           CMAKE_GENERATOR: "Unix Makefiles"
+          CMAKE_BUILD_PARALLEL_LEVEL: 6
+          CTEST_PARALLEL_LEVEL: 6
+          SKBUILD_BUILD_DIR: "/Users/runner/work/OpenImageIO/OpenImageIO/build"
+          CCACHE_DIR: /Users/runner/.ccache
+          CCACHE_COMPRESSION: yes
+
+      - name: ccache-save
+        id: ccache-save
+        uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
+        with:
+          path: ~/.ccache
+          key: wheel-${{runner.os}}-${{matrix.python}}
 
       - uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
         with:
@@ -400,6 +512,11 @@ jobs:
           CIBW_BUILD: ${{ matrix.python }}
           CIBW_ARCHS: ${{ matrix.arch }}
           CMAKE_POLICY_VERSION_MINIMUM: 3.5
+          CMAKE_BUILD_PARALLEL_LEVEL: 4
+          CTEST_PARALLEL_LEVEL: 4
+          SKBUILD_BUILD_DIR: "$HOME/OpenImageIO/OpenImageIO/build"
+          CCACHE_DIR: ~/.ccache
+          CCACHE_COMPRESSION: yes
 
       - uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
         with:
